### ISSUE TITLE
Thesis experiment question

### ISSUE THREAD

**Issue by 12moli** [Seyedhosseinzadeh/SUCP#1]
"Leveraging Social Influence based on Users Activity Centers for Point-of-Interest Recommendation."This paper shows the precision of experimental section and the recall rate is how to calculate?Is this the average value of all users?

**Comment by Seyedhosseinzadeh** [comment]
In the evaluation section of the paper, you can see the average precision and recall of all users (as you see in code, line 197 of recommendation.py). However, we wrote every user's precision and recall separately as a .txt result file for other evaluation that we needed (line 205).

**Comment by 12moli** [comment]
Thank you very much for your reply！ For the STACP code I ran, the average precision of all users(Precision@10) calculated using the Gowalla dataset is only 0.0236. Do I need to change the source code to reach 0.0383 precision?

**Comment by Seyedhosseinzadeh** [comment]
You're welcome! The beta parameter is an important factor. you should use a different beta parameter for each dataset.

**Comment by 12moli** [comment]
Ok, I'll try again.

**Comment by 12moli** [comment]
I have tested the Yelp dataset with beta=0.8. I found that the code in line 197 only calculates the precision for one user, so I ended up summing the precision for all users and taking the mean value, and the Precision@10 is only 0.0003, which is very different from the accuracy in the paper. Do I need to make any changes to the code, or is there something I have misunderstood? I look forward to hearing from you, or you can email me at ljt18153427985@163.com.
